services:
  backend:
    build: ./backend
    container_name: roadvision-backend
    ports:
      - "8085:8085"
    restart: always

  frontend:
    build: ./frontend
    container_name: roadvision-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
